import { ASSETS } from './assets';

export const categories = [
  { id: 'all', name: 'All Products', icon: 'LayoutGrid', color: 'text-[#8b5cf6]' },
  { id: 'apps', name: 'Apps', icon: 'Smartphone', color: 'text-emerald-400' },
  { id: 'websites', name: 'Websites', icon: 'Globe', color: 'text-sky-400' },
  { id: 'custom', name: 'Custom Apps', icon: 'Code', color: 'text-purple-400' },
  { id: 'source', name: 'Source Code', icon: 'FileCode', color: 'text-violet-400' },
];

export const products = [
  {
    id: '1',
    title: 'E-Commerce App',
    description: 'Premium e-commerce app with complete admin panel',
    category: 'Apps',
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.9,
    reviews: 1250,
    sales: '1.2K',
    image: ASSETS.ecommercePhones,
    images: [
      ASSETS.ecommercePhones,
      ASSETS.foodDelivery,
      ASSETS.realEstate,
      ASSETS.chatApp,
    ],
    features: [
      'Complete Mobile App',
      'Admin Panel (Web)',
      'Backend API',
      'Lifetime Updates',
      '6 Months Support',
      'Documentation Included',
    ],
    version: '1.0.0',
    isSale: true,
  },
  {
    id: '2',
    title: 'Food Delivery App',
    description: 'Complete food delivery solution with tracking',
    category: 'Apps',
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.8,
    reviews: 950,
    sales: '950',
    image: ASSETS.foodDelivery,
    images: [
      ASSETS.foodDelivery,
      ASSETS.ecommercePhones,
      ASSETS.realEstate,
    ],
    features: [
      'Customer & Driver Apps',
      'Live GPS Tracking',
      'Stripe & PayPal Gateway',
      'Restaurant Admin Portal',
      'Push Notifications',
      'Full Source Code',
    ],
    version: '2.1.0',
    isSale: false,
  },
  {
    id: '3',
    title: 'Real Estate Website',
    description: 'Full featured real estate website with map search',
    category: 'Websites',
    price: 39.99,
    originalPrice: 65.00,
    rating: 4.7,
    reviews: 870,
    sales: '870',
    image: ASSETS.realEstate,
    images: [
      ASSETS.realEstate,
      ASSETS.marketplaceWeb,
      ASSETS.portfolioWeb,
    ],
    features: [
      'Interactive Map Search',
      'Agent Management',
      'Virtual Tour Embeds',
      'SEO Optimized',
      'Responsive Design',
      'Easy Customization',
    ],
    version: '1.4.2',
    isSale: false,
  },
  {
    id: '4',
    title: 'Chatting App',
    description: 'Real-time chatting app with admin panel',
    category: 'Apps',
    price: 34.99,
    originalPrice: 49.99,
    rating: 4.8,
    reviews: 760,
    sales: '760',
    image: ASSETS.chatApp,
    images: [
      ASSETS.chatApp,
      ASSETS.ecommercePhones,
      ASSETS.fitnessApp,
    ],
    features: [
      'End-to-End Encryption',
      'Voice & Video Calls',
      'Group Chats & Channels',
      'Media Sharing',
      'Firebase Backend',
      'Clean MVVM Architecture',
    ],
    version: '3.0.1',
    isSale: false,
  },
  {
    id: '5',
    title: 'School Management App',
    description: 'Complete school management solution',
    category: 'Custom Apps',
    price: 44.99,
    originalPrice: 69.99,
    rating: 4.9,
    reviews: 650,
    sales: '650',
    image: ASSETS.schoolApp,
    images: [
      ASSETS.schoolApp,
      ASSETS.realEstate,
      ASSETS.marketplaceWeb,
    ],
    features: [
      'Student & Teacher Portals',
      'Attendance Tracking',
      'Gradebook & Report Cards',
      'Fee Collection System',
      'Parent Communication App',
      'Role-based Permissions',
    ],
    version: '2.0.0',
    isSale: false,
  },
  {
    id: '6',
    title: 'Portfolio Website',
    description: 'Modern portfolio website template with dark mode',
    category: 'Websites',
    price: 24.99,
    originalPrice: 39.99,
    rating: 4.7,
    reviews: 540,
    sales: '540',
    image: ASSETS.portfolioWeb,
    images: [
      ASSETS.portfolioWeb,
      ASSETS.marketplaceWeb,
      ASSETS.realEstate,
    ],
    features: [
      'Modern Bento Layout',
      'Dark Neon Aesthetic',
      'Interactive Project Showcase',
      'Contact Form Integration',
      'Ultra Fast 100 Lighthouse Score',
      'Tailwind CSS & React',
    ],
    version: '1.2.0',
    isSale: false,
  },
  {
    id: '7',
    title: 'Multi Vendor Marketplace',
    description: 'Complete multivendor marketplace solution',
    category: 'Source Code',
    price: 69.99,
    originalPrice: 99.99,
    rating: 4.9,
    reviews: 430,
    sales: '430',
    image: ASSETS.marketplaceWeb,
    images: [
      ASSETS.marketplaceWeb,
      ASSETS.ecommercePhones,
      ASSETS.realEstate,
    ],
    features: [
      'Multi-Vendor Dashboard',
      'Commission Management',
      'Product Reviews & Ratings',
      'Multi-Currency Support',
      'Automated Payouts',
      'Complete React & Node Stack',
    ],
    version: '4.0.0',
    isSale: false,
  },
  {
    id: '8',
    title: 'Fitness App',
    description: 'Fitness & workout app with admin panel',
    category: 'Apps',
    price: 37.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 380,
    sales: '380',
    image: ASSETS.fitnessApp,
    images: [
      ASSETS.fitnessApp,
      ASSETS.chatApp,
      ASSETS.foodDelivery,
    ],
    features: [
      'Workout Planner & Routines',
      'Calorie & Macro Tracker',
      'Progress Graphs & History',
      'Video Exercise Guides',
      'Wearable Sync Support',
      'Admin Content CMS',
    ],
    version: '1.5.0',
    isSale: false,
  },
];
